# -*- coding: utf-8 -*-
"""resume.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11iJZbivvwQYlacVpf0Zqg4bEjWRtKvok
"""
#requirement resume should be defined format
#requirement one word skills only 
#doesnt handle b.tech 
import os
import condition_checker
res=[]
condition=[]
def set_condition(filter):
    global condition
    condition.append(input("enter " + filter+": "))
def scanner(path):
    while True:
                filter1=[""]
                global condition
                print("apply the following filters on resume 1.degree 2.skills 3.experience to exit type 0 enter space separated numbers for multiple filters example 1 2 for degree and skill filter:")
                choice=-1
                choice=input("enter choice")
                if choice=="0": 
                        exit()
                elif choice=="1":
                        set_condition("degree")
                        filter1[0]="degree"
                        
                        
                elif choice=="2":
                    set_condition("skills")
                    filter1[0]="skills"  
                elif choice=="3":
                        set_condition("number of years of  experience (use > or < or = or combination)")
                        filter1[0]="total_exp"
                elif choice=="1 2":
                        set_condition("degree")
                        set_condition("skills")
                        filter1[0]="degree"
                        filter1.append("skills")
                elif choice=="2 3":
                        set_condition("skills")
                        set_condition("number of years of  experience (use > or < or = or combination)")
                        filter1[0]="skills"
                        filter1.append("total_exp")
                elif choice=="1 3":
                        set_condition("degree")
                        set_condition("number of years of  experience (use > or < or = or combination)")
                        filter1[0]="degree"
                        filter1.append("total_exp")
                elif choice=="1 2 3":
                        set_condition("degree")
                        set_condition("skills")
                        set_condition("number of years of  experience (use > or < or = or combination)")
                        filter1[0]="degree"
                        filter1.append("skills")
                        filter1.append("total_exp")
                else:
                        print("enter valid choice")
                        break
                for text in os.listdir(path):
                    global res
                    resume1=open(path+text,"r")
                    resume2=resume1.read().splitlines() 
                    resume3=[i.split(":") for i in resume2]
                    for i in resume3:
                        if i==" ":
                            resume3.remove(i)
                    res_dct = {resume3[i][0]: resume3[i][1] for i in range(0, len(resume3), 1)}
                    count=0
                    #print(filter1)
                    for i in range(len(filter1)):
                        res.append(condition_checker.check_condition(res_dct,condition[i],filter1[i].lower()))
                        if res[i]:
                            print(res[i],"dbg")
                            count+=1
                        elif res=="invalid":
                                print("enter valid inputs (and or conditions only)")
                        elif res=="-1":
                                print("error: "+text +"resume format incorrect")
                    res.clear()
                    
                    if count==len(filter1):
                                print(text," satisfies the requirement")
                
                    else:
                                print(text,"doesnt satisfy requirement")
                condition.clear()
                    
                
                #invalid inputs rest of the numbers
                #try path in c drive


